Update dev_ci_cd_pipelline.yml

diff --git a/.github/workflows/dev_ci_cd_pipelline.yml b/.github/workflows/dev_ci_cd_pipelline.yml
--- a/.github/workflows/dev_ci_cd_pipelline.yml
+++ b/.github/workflows/dev_ci_cd_pipelline.yml
@@ -106,31 +106,34 @@ jobs:
           # hostname, network alias set for container to container comms
           # default port exposed for runner to container comms (verify container is up)
 
-          #echo "docker run --name $SAW_TARGET_NAME \
-          #  --hostname $SAW_TARGET_NAME \
-          #  --network $DOCKER_NETWORK \
-          #  --network-alias $SAW_TARGET_NAME \
-          #  -p 3000:3000 \                                                                
-          #  -d $SAW_TARGET_NAME"
+          ### DEBUG ###
+          echo "docker run --name $SAW_TARGET_NAME \
+            --hostname $SAW_TARGET_NAME \
+            --network $DOCKER_NETWORK \
+            --network-alias $SAW_TARGET_NAME \
+            -p $SAW_TARGET_PORT:$SAW_TARGET_PORT \                                                                
+            -d $SAW_TARGET_NAME"
           
           docker run --name $SAW_TARGET_NAME \
             --hostname $SAW_TARGET_NAME \
             --network $DOCKER_NETWORK \
             --network-alias $SAW_TARGET_NAME \
-            -p 3000:3000 \
+            -p $SAW_TARGET_PORT:$SAW_TARGET_PORT \
             -d $SAW_TARGET_NAME
 
       # Step 6: Wait for the app to start & test with curl
       - name: Test application with curl
         run: |
-          echo "curl -s -o /dev/null -w \"%{http_code}\" $SAW_TARGET_PROTO://127.0.0.1:$SAW_TARGET_PORT"
-          
+         
           # Make a request to the web app using the custom hostname
           RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" $SAW_TARGET_PROTO://127.0.0.1:$SAW_TARGET_PORT)
+
+          ### DEBUG ###
+          echo "curl -s -o /dev/null -w \"%{http_code}\" $SAW_TARGET_PROTO://127.0.0.1:$SAW_TARGET_PORT"
            
           if [ "$RESPONSE" -ne 200 ]; then
-            echo "App test failed with HTTP status $RESPONSE";
-            exit 1;
+             echo "App test failed with HTTP status $RESPONSE";
+             exit 1;
           fi
 
           echo "App test passed with HTTP status $RESPONSE";
